"""Tests for the swagger-generated v2 telemetry wire types.

The companion module ``aioabrp._wire_types`` is generated by
``datamodel-code-generator`` from ABRP's v2 OpenAPI spec and checked into
the repo (no runtime codegen dep). These tests pin the **keep-set** the
library actually consumes — every leaf reachable from ``OutputPoint``
via the :mod:`aioabrp._extract` metric registry, plus the exact
cardinality of ``OutputPoint``'s surfaced fields — so a swagger drift,
accidental hand-edit, or sloppy regen-without-prune fails fast.

The ``OutputPoint`` cardinality assertion below doubles as the
swagger-drift canary referenced by ``_wire_types.py``'s
regen-then-prune header: if a future regen re-introduces a pruned field
and the prune step is forgotten, this test goes loudly RED rather than
the library silently shipping ~3k LOC of generated noise.

Parametrize floor is one row per surfaced leaf (26 entries) —
representative-shape would blind the suite to per-leaf wire-key drift
(e.g. codegen renaming ``frac`` to ``percent`` on ``Soh`` only).
"""

from typing import get_type_hints, is_typeddict

import pytest

from aioabrp._wire_types import (
    BatteryCapacity,
    BatteryTemperature,
    CabinSetPoint,
    CabinTemperature,
    CalibratedConfidence,
    CalibratedRefCons,
    ChargingEnergyAdded,
    ChargingState,
    Current,
    DrivingState,
    Elevation,
    EstimatedBatteryRange,
    ExternalTemperature,
    Heading,
    HvacPower,
    Location,
    LocationOutput,
    MapInfo,
    MaxSpeed,
    Odometer,
    OutputPoint,
    OutputPointWithVehicleId,
    Power,
    Soc,
    Soe,
    Soh,
    Speed,
    SpeedFactor,
    Voltage,
)

# Wire-key keep-set: every leaf TypedDict that the metric extractors in
# ``aioabrp._extract`` read, including ``Location`` (consumed by the
# ``Metric.LOCATION`` extractor). ``Location`` carries two axes
# (``lat`` + ``long``); every other leaf carries one.
_KEEP_SET_LEAVES: tuple[tuple[type, frozenset[str]], ...] = (
    (Soc, frozenset({"frac"})),
    (Power, frozenset({"w"})),
    (Voltage, frozenset({"v"})),
    (Soe, frozenset({"wh"})),
    (Odometer, frozenset({"m"})),
    (CalibratedRefCons, frozenset({"wh_per_km"})),
    (BatteryCapacity, frozenset({"wh"})),
    (Soh, frozenset({"frac"})),
    (EstimatedBatteryRange, frozenset({"m"})),
    (BatteryTemperature, frozenset({"c"})),
    (ChargingState, frozenset({"state"})),
    (Location, frozenset({"lat", "long"})),
    # The 14 leaves added to reach the full 26-field OutputPoint mirror.
    (CabinSetPoint, frozenset({"c"})),
    (CabinTemperature, frozenset({"c"})),
    (MaxSpeed, frozenset({"ms"})),
    (ChargingEnergyAdded, frozenset({"wh"})),
    (Current, frozenset({"a"})),
    (DrivingState, frozenset({"state"})),
    (Elevation, frozenset({"m"})),
    (ExternalTemperature, frozenset({"c"})),
    (Heading, frozenset({"degrees"})),
    (HvacPower, frozenset({"w"})),
    (Speed, frozenset({"ms"})),
    (SpeedFactor, frozenset({"frac"})),
    (CalibratedConfidence, frozenset({"frac"})),
    (
        MapInfo,
        frozenset(
            {"region", "country_3", "address", "speedLimitMs", "isFreeSpeedZone"}
        ),
    ),
)

# The 26 surfaced keys on ``OutputPoint`` after pruning. Anything other
# than this exact set is a drift signal: extra keys = generator
# re-introduced a pruned field (regen-without-prune); missing keys =
# accidental over-prune dropped a surfaced field.
_EXPECTED_OUTPUT_POINT_KEYS: frozenset[str] = frozenset(
    {
        "soc",
        "power",
        "voltage",
        "soe",
        "odometer",
        "calibratedRefCons",
        "batteryCapacity",
        "soh",
        "estimatedBatteryRange",
        "batteryTemperature",
        "chargingState",
        "location",
        "cabinSetPoint",
        "cabinTemperature",
        "calibratedMaxSpeed",
        "chargingEnergyAdded",
        "current",
        "drivingState",
        "elevation",
        "externalTemperature",
        "heading",
        "hvacPower",
        "mapInfo",
        "speed",
        "speedFactor",
        "calibratedConfidence",
    }
)


def test_output_point_is_typeddict() -> None:
    """``OutputPoint`` is a TypedDict (not a dataclass or NamedTuple)."""
    assert is_typeddict(OutputPoint)


def test_output_point_with_vehicle_id_is_typeddict() -> None:
    """``OutputPointWithVehicleId`` is a TypedDict."""
    assert is_typeddict(OutputPointWithVehicleId)


@pytest.mark.parametrize(
    ("leaf_cls", "expected_keys"),
    [pytest.param(leaf, keys, id=leaf.__name__) for leaf, keys in _KEEP_SET_LEAVES],
)
def test_keep_set_leaf_typeddict(leaf_cls: type, expected_keys: frozenset[str]) -> None:
    """Each surfaced leaf is a TypedDict carrying EXACTLY its wire key(s).

    Parametrize floor is one row per surfaced leaf so a per-leaf
    wire-key drift (e.g. codegen renaming ``frac`` to ``percent`` on
    ``Soh`` only) goes RED — the matching extractor would otherwise
    return ``None`` silently. Exact equality (not subset) so a regen
    that ADDS a key to a kept leaf goes RED too.
    """
    assert is_typeddict(leaf_cls)
    assert get_type_hints(leaf_cls).keys() == expected_keys


def test_output_leaf_carries_mixin_chain_keys() -> None:
    """The ``WithTime``/``WithTimeAndProvider`` mixin chain survives pruning.

    Every ``XxxOutput`` leaf inherits ``time`` and ``provider`` through
    the mixin chain; pin it on one representative so losing the mixins
    (or their keys) goes RED.
    """
    assert {"time", "provider", "lat", "long"} <= get_type_hints(LocationOutput).keys()


def test_output_point_cardinality_pins_surfaced_keys() -> None:
    """``OutputPoint`` exposes EXACTLY the 26 surfaced wire keys.

    Doubles as a swagger-drift canary per the regen-then-prune header in
    ``_wire_types.py``: if a future regen forgets the prune step,
    cardinality jumps from 26 to the full graph and this assertion goes RED.
    """
    assert set(get_type_hints(OutputPoint)) == set(_EXPECTED_OUTPUT_POINT_KEYS)


def test_output_point_with_vehicle_id_extends_with_vehicle_id() -> None:
    """``OutputPointWithVehicleId`` adds ``vehicleId`` on top of ``OutputPoint``."""
    assert set(get_type_hints(OutputPointWithVehicleId)) == (
        set(_EXPECTED_OUTPUT_POINT_KEYS) | {"vehicleId"}
    )
